pytest_pylint.py
test_pytest_pylint.py

Allows to setup custom error string format.
Deprecated pylintrc options like "include-ids" and "symbols" are not
supported.

use msg-template from pylintrc config to format error

---

pytest_pylint.py
test_pytest_pylint.py

I could not set relative `.pylint.rc` in `pytest.ini` file.
FYI: the **pytest** finds their `pytest.ini`, but it will not set CWD.

Find .pylintrc in directory of pytest.ini too

---

setup.py

test_pytest_pylint.py is failing on 2.6.4 and older

Bump required version pytest to 2.7

---

README.rst
pytest_pylint.py

You can run `py.test --pylint -m pylint` to just run the linter and no
other tests.
This functionality is directly adopted from https://github.com/fschulze/pytest-flakes .

Add marker 'pylint' to run pylint checks only

---

pytest_pylint.py

This change moves the run of the linter to occur after the collection but before the rest of the tests.  This offers two advantages:
1. By running the linter over all files concurrently, messages such as duplicate-code can be picked up which was not possible previously.
2. pytest-pylint currently clashes with pytest-cov in that when both are activate linting takes 10x longer than normal.  On my project of 83 files linting takes ~690 seconds.  This seems to be due to the traceback behaviour of coverage clashing with how astroid assesses syntax.  As long as the linter is run within the Items this will always be a problem.  By moving the linter ahead of the test run, and altering pytest-cov to start the coverage run later, the clash should be avoidable.

Prerun linter

---

pytest_pylint.py
test_pytest_pylint.py

Added flag to temporarily disable pylint

---

pytest_pylint.py
test_pytest_pylint.py

Addresses a minor lingering issue to #62 (thanks for the fix, btw, confirmed that it works for our internal project).
I've pushed another repro commit to https://github.com/jamur2/pytest-repro demonstrating that the test output only shows the test name but not the full relative path to some failing files.
Prior to this PR:
```
± pipenv run pytest
============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.7.0, pytest-3.7.4, py-1.6.0, pluggy-0.7.1
rootdir: /Users/jackie.murphy/rally/pylint-repro, inifile: pytest.ini
plugins: pylint-0.12.2
collected 3 items
-----------------------------------------------------------------
Linting files
... …
```

Show full relative path to file under test

---

pytest_pylint.py
test_pytest_pylint.py

As mentioned, here's my suggested fix for issue #71.  I've added a unit test to check include_path for a number of potential paths.  I've assumed Linux paths as that seems to follow the test for get_rel_path.
When I ran my tests through Travis it appears that test_basic is failing on Python 2.7.  As far as I can see this seems to be coming from a deprecation warning being triggered by configparser.  I'm also seeing this in the Travis run for master (which is at commit a5e9784587).  I'm assuming this is related to the upgrade in pytest from 3.7.4 in your latest run on master and 3.8.0 in mine as there seems to have been some work in capturing & displaying warnings there.

Fix issue #71

---

pylintrc
pytest_pylint.py
test_pytest_pylint.py

The `pylint` is too slow, especially when the project is large.
[pytest-flakes](https://github.com/fschulze/pytest-flakes) can skip unchanged checked files by pytest cache.
This implementation is learned from that.

Skip unchanged files which is checked

---

pytest_pylint.py
test_pytest_pylint.py

The issue is #91.
I don't know someone depends on `-p no:cacheprovider`, so I didn't realize the `config.cache` could be missing. Sorry about that.
In this pull request, I add a regression test to reproduce that issue, and fix it with checking.
The pytest-pep8 has the same problem. As a result, for pytest-pylint its self, `--pep8` in `tox.ini` should be deleted, before `pytest -p no:cacheprovider` is run.

Fix the crash when `-p no:cacheprovider` is given.

---

pytest_pylint.py
tox.ini

Some other linter plugins will display a hint in `pytest --verbose`.
```
setup.py::YAPF PASSED
setup.py PASSED
setup.py::FLAKE8 PASSED
setup.py::ISORT PASSED
```
It is convenient with multiple linters and complex ignores.
[pytest_flake8.py#L90] is referenced.
[pytest_flake8.py#L90]:https://github.com/tholo/pytest-flake8/blob/c485d5e85ac6b2138405378e9763e7025f58b023/pytest_flake8.py#L90

Add ::PYLINT in pytest verbose mode

---

pytest_pylint/plugin.py
pytest_pylint/tests/test_pytest_pylint.py
setup.py
tox.ini

pylint 2.5 (unreleased) can read its config also from `pyproject.toml` and `setup.cfg`. See PyCQA/pylint#3169 for details.
This PR adds support for`pyproject.toml`.

Add support for pyproject.toml as pylint config file

---

pytest_pylint/plugin.py
pytest_pylint/tests/test_pytest_pylint.py

I cleaned up https://github.com/carsongee/pytest-pylint/pull/99 to pass the arguments directly into pylint to enable overriding the file configuration

Cleanup PR #99

---

pytest_pylint/plugin.py

Avoid name collisions by using the full rel_path instead of the simple name.

fix: #117 use rel_path instead of name for the mtimes lookup

---

setup.py

With pytest less than `5.4`, there will be errors below:
```shell
$ pytest
==================================== test session starts =====================================
platform linux -- Python 3.5.3, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /tmp/pytest-pylint, inifile: tox.ini
plugins: flake8-1.0.5, pylint-0.16.0
collected 0 items / 1 error                                                                  
=========================================== ERRORS ===========================================
_______________________________ ERROR collecting test session ________________________________
.env/lib/python3.5/site-packages/pluggy/hooks.py:286: in __call__
return self._hookexec(self, self.get_hookimpls(), kwargs)
.env/lib/python3.5/site-packages/pluggy/manager.py:93: in _hookexec …
```

Fix versions of pytest and pylint in install_requires

---

pytest_pylint/plugin.py
setup.py

https://github.com/PyCQA/pylint/blob/master/ChangeLog
What's New in Pylint 2.5.1?
===========================
Release date: 2020-05-05
* Fix a crash in `method-hidden` lookup for unknown base classes
Close #3527
* Revert pylint.Run's `exit` parameter to ``do_exit``

pylint 2.5.1 contains breaking changes. rename do_exit => exit

---

pytest_pylint/plugin.py

Due to the resulting in potential false passes.
See the following for more details:
https://github.com/pymedphys/pymedphys/issues/1305#issuecomment-761517891

Remove runtime error lines

---

pytest_pylint/plugin.py
pytest_pylint/tests/test_pytest_pylint.py

Changes the way that the config file is retrieved from pylint.config. Previously
this was done using the static `variable pylint.config.PYLINTRC` which is defined
at load by iterating over all the files found via
`pylint.config.find_default_config_files()` until one ending in "pylintrc" is
found. In pylint itself config seems instead to be found by calling
`next(find_default_config_files(), None)` which is also able to find setup.cfg or
pyproject.toml based config files automatically. I have thus changed PyLintPlugin
to use the same version and can now call `py.test --pylint` and have config from
my pyproject.toml picked up correctly.
I have added one additional test, essentially copying the existing
`test_pylint_file_toml`, but now called `test_pyline_file_pyproject_toml`, which
is …

feat: auto-find config that is not pylintrc based

---

.github/workflows/tests.yml
pytest_pylint/plugin.py
pytest_pylint/pylint_util.py
setup.py
tox.ini

This is primarily to fix things in order to work with pylint 3. I plan to release from here, and then rapidly make another release that drops support for Pre 2.6 pylint and pre 7.0 pytest as well. I just wanted to get something out there that will fix folks for pylint 3.0 without breaking folks with older pytest

Updates for new Python, Drop Py 3.7, and Support Pylint 3.x

---

pytest_pylint/plugin.py

Fixes compatibility with pytest 8.1, see
- pytest-dev/pytest#8144
- https://docs.pytest.org/en/stable/changelog.html#id282
- https://docs.pytest.org/en/stable/deprecations.html#py-path-local-arguments-for-hooks-replaced-with-pathlib-path
Fixes carsongee/pytest-pylint#192

Use `pathlib.Path` in plugin hooks

---

.github/workflows/tests.yml

Fixes:
Node.js 16 actions are deprecated. Please update the following
actions to use Node.js 20: actions/checkout@v3,
actions/setup-python@v3. For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
The test failures are unrelated.  I'm happy to rebase once they are fixed. :)

Use latest actions in GitHub Actions
